---
title: "Harvard College Enrollment Trends"
author: "Westley and Alex"
date: "3/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(readxl)
library(gt)

enrollment_current <- read_excel("raw-data/class_enrollment_summary_by_term_2.25.20_0.xlsx",
                               skip = 3) %>% 
  clean_names() %>% 
  filter(!is.na(course_name))

enrollment_spring_2019 <- read_excel("raw-data/class_enrollment_summary_by_term_3.22.19_0.xlsx",
                               skip = 3) %>% 
  clean_names() %>% 
  filter(!is.na(course_name)) %>% 
  select(course_id)

```

```{r enrollment, echo=FALSE}

enrollment_current %>% 
  anti_join(enrollment_spring_2019, by = "course_id") %>% 
  arrange(desc(total)) %>% 
  slice(1:5) %>% 
  select(course_title, course_name, course_department, instructor_full_name, total) %>% 
  gt() %>% 
  tab_header(title = "Five Biggest New Courses at Harvard, Spring 2020") %>% 
  tab_footnote(footnote = "Data from Registrar Office",
               locations = cells_title("title")) %>% 
  cols_label(course_title = "Course Title",
             course_name = "Course Name",
             course_department = "Department",
             instructor_full_name = "Instructor",
             total = "Total Enrollment")

```

